atmos/atmos/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^fpi/', include('fpi.urls')),
    #url(r'^$', 'atmos.views.home', name='home'),
    # url(r'^atmos/', include('atmos.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls), name='admin-view'),
     
)


from django.conf import settings

if settings.DEBUG:
    urlpatterns += patterns('',
                           (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                            {'document_root': settings.MEDIA_ROOT}),
                           )

atmos/fpi/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from models import fpProject
import views

projects = {
        'queryset' : fpProject.objects.all(),
        }

urlpatterns = patterns('django.views.generic.list_detail',
    # Species:
    url(R'^species/(?P<pk>\d+)/$', views.fpSpeciesDetailView.as_view(), name='species-detail'),
    
    # Tracers:
    url(R'^tracer/(?P<pk>\d+)/$', views.fpTracerDetailView.as_view(), name='tracer-detail'),
    
    # Runs
    url(r'^$', 'object_list', projects, name='project-list'),
    
    url(R'^project/(?P<slug>\w+)/$', views.fpProjectDetailView.as_view(), name='project-detail'),
    
    url(R'^run/(?P<pk>\w+)/$', views.fpRunDetailView.as_view(), name='run-detail'),
    #url(R'^(?P<object_id>\d+)/interactive/(?P<tracer_id>\d+)/$', direct_to_template, {'template': 'fpi/fprun_entry.html'}),
    url(R'^interactive/$', views.fpRunInteractive.as_view(), name='fp-interactive'),
    url(R'^interactive/instructions/(?P<slug>\w+)/$', views.fpRunInstructionDetailView.as_view(), name='fp-instructions'),
    url(R'^interactive/(?P<slug>\w+)/(?P<runslug>\S+)/$', views.fpRunInteractive.as_view(), name='fp-interactive'),
    url(R'^interactive/(?P<slug>\w+)/$', views.fpRunInteractive.as_view(), name='fp-interactive'),
   
    url(R'^ajax/$', views.header_ops, name='ops'),
    
    
    url(R'^fpi_view/$', views.fpRunInteractive.as_view(), name='fpi-view'),
    #url(R'^fpi_view/$', views.fpRunInteractive.as_view(), name='fpi-view'),
    
    #url(R'^contact/$', views.contact, name='contact'),
    #url(R'^fpi_view/img/(?P<fmt>\w+)$', views.image, name='img'),
    
    )

atmos/fpi/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField()
    email = forms.EmailField(required=False)
    message = forms.CharField(widget=forms.Textarea)


class InteractivePlotForm(forms.Form):
    
    def __init__(self, proj_set=None,
                 header=None,
                 *args, **kwargs):
            
        super(InteractivePlotForm, self).__init__(*args, **kwargs)
        
        
        if proj_set is not None:
            ## Which projects / runs are available
            self.fields['project'].choices = [(d.slug, d) for d in proj_set['projects']]
            self.initial['project'] = proj_set['projslug']
            
            self.fields['run'].choices = [(d.slug, d) for d in proj_set['runs']]
            self.initial['run'] = proj_set['runslug']
            
            # Hidden Elements
            self.initial['projectID'] = proj_set['projslug']
            self.initial['run_dir'] = proj_set['run_dir']
            
            
        
        if header is not None:
            # Widgets generated from Header Input
            
            ## Initialize Lat / Lon Boxes
            self.fields['llcrnrlat'].initial = header.latitude[1]
            self.fields['llcrnrlon'].initial = header.longitude[1]
            self.fields['urcrnrlat'].initial = header.latitude[-2]
            self.fields['urcrnrlon'].initial = header.longitude[-2]
            self.fields['l_lat'].initial = header.latitude[1]
            self.fields['l_lon'].initial = header.longitude[1]
            self.fields['r_lat'].initial = header.latitude[-2]
            self.fields['r_lon'].initial = header.longitude[-2]
            
            
            ## Initialize Date Select Fields
            self.fields['p_start'].choices = [(d, d) for d in header.available_dates_dt]
            self.initial['p_start'] = self.fields['p_start'].choices[-1][1]
            self.fields['p_end'].choices = [(d, d) for d in header.available_dates_dt]
            
            ## Ageclass
            if header.direction == 'forward':
                choices = [(0, 'all')]
            else:
                choices = [(i, d) for i, d in enumerate(header.ageclasses.insert(0, 'all'))]
                
            self.fields['ageclass'].choices = choices
    
            ## Which tracer/species to plot
            self.fields['tracer'].choices = [(i, d) for i, d in enumerate(header.species)]
            
            ## Which level
            self.fields['level'].choices= \
                            [(0,'Total Column'), (1, 'Footprint')] + \
                            [(i+2, d) for i, d in enumerate(header.outheight)]
            

    
            ## Do we display the releases widget?
            if header.numpointspec > 1:
                self.fields['numpointspec'].choices = [(d+1, d+1) for d in xrange(header.numpointspec)]
    
            else:
                self.fields['numpointspec'].choices = [(1,1)]
                self.initial['numpointspec'] = 1
                self.fields['numpointspec'].widget = forms.HiddenInput()
                
                self.has_multiple_nps = False
                
            self.header = header
    
    
    has_multiple_nps = True

    # Generated for proj_set
    run = forms.ChoiceField( widget=forms.Select(attrs={'id':'runs'}))
    project = forms.ChoiceField( widget=forms.Select(attrs={'id':'projects'}))
    
    # Widgets generated from Header Input
    tracer = forms.ChoiceField()
    p_start = forms.ChoiceField()
    p_end = forms.ChoiceField(required=False)
    ageclass = forms.ChoiceField()
    numpointspec = forms.ChoiceField()
    level = forms.ChoiceField()

    # File upload option
    plotfile = forms.FileField( required=False )
    flight_movie = forms.BooleanField(required=False)
    timeseries = forms.BooleanField(required=False)

    # Map Paramters
    llcrnrlat = forms.FloatField(initial=23.0)
    llcrnrlon = forms.FloatField(initial=23.0)
    urcrnrlat = forms.FloatField(initial=23.0)
    urcrnrlon = forms.FloatField(initial=23.0)
    l_lat = forms.FloatField(initial=23.0)
    l_lon = forms.FloatField(initial=23.0)
    r_lat = forms.FloatField(initial=23.0)
    r_lon = forms.FloatField(initial=23.0)

    # Hidden Elements
    run_dir = forms.CharField(required=False, widget=forms.HiddenInput())
    projectID = forms.CharField(required=False, widget=forms.HiddenInput())
        

    # Option Fields
    animate = forms.ChoiceField(choices= \
                                [('single', 'single'), ('movie', 'movie')],
                                required=False)
    plot_type = forms.ChoiceField(choices= \
                                [('both', 'both'), ('horizontal', 'horizontal'), ('vertical', 'vertical')])
    unit = forms.ChoiceField(choices= \
                                [('conc', 'concentration (ug m-3)'), ('pptv', 'mixing ratios (ppbv)')])
    
    max_conc = forms.FloatField(required=False)
    min_conc = forms.FloatField(required=False)
    nest = forms.BooleanField(initial=False, required=False)
    asl = forms.BooleanField(required=False)
    log = forms.BooleanField(initial=True, required=False)
    crossmethod = forms.ChoiceField(choices = \
                                    [('pcolormesh', 'no interp'), ('contourf', 'interp')])

atmos/fpi/views.py
# Create your views here.

import sys, os
import json
from datetime import datetime

sys.path.append('/home/jfb/workspace')
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.views.generic import DetailView, CreateView
from django.http import Http404, HttpResponse, HttpResponseRedirect


from models import fpProject, fpRun, fpTracer, fpSpecies
from forms import InteractivePlotForm
from django.conf import settings

from nilu.pflexpart import pflexpart as pf
from nilu.pflexpart import fpi
np = pf.np

def home(request):
    pass

class fpSpeciesDetailView(DetailView):

    queryset = fpSpecies.objects.all()
    context_object_name = "fpSpecies"
    template_name = 'fpi/fpspecies_detail.html'


class fpTracerDetailView(DetailView):

    queryset = fpTracer.objects.all()
    context_object_name = "fpTracer"
    template_name = 'fpi/fptracer_detail.html'

    def get_context_data(self, **kwargs):

        context = kwargs
        context_object_name = self.get_context_object_name(self.object)

        if context_object_name:
            context[context_object_name] = self.object

        speciesQS = fpSpecies.objects.all()
        spc = speciesQS.filter(**{'species_name': self.object.species}).get()
        context['species'] = spc

        return context


class fpRunDetailView(DetailView):

    queryset = fpRun.objects.all()
    context_object_name = "fpRun"
    template_name = 'fpi/fprun_detail.html'


class fpProjectDetailView(DetailView):

    queryset = fpProject.objects.all()
    context_object_name = "fpProject"
    template_name = 'fpi/fpproject_detail.html'


class fpRunInstructionDetailView(DetailView):

    queryset = fpProject.objects.all()
    context_object_name = "fpProject"
    template_name = 'fpi/fpproject_instructions.html'


class fpRunInteractive(CreateView, DetailView):

    queryset = fpProject.objects.all()
    context_object_name = "fpRunInteractive"
    template_name = 'fpi/fpi_interactive.html'
    settings = settings
    
    
    def get_object(self, queryset=None):
        """
        Returns the object the view is displaying.

        Overrides default get_object from 
        File /home/jfb/Dev_Web/django-trunk/django/views/generic/list_detail.py
        """
        # Try to get object from query set.
        
        
        slug = self.kwargs.get('slug', None)
        runslug = self.kwargs.get('runslug', None)
        
        super(fpRunInteractive, self).get_object(queryset=queryset)
        # Use a custom queryset if provided; this is required for subclasses
        # like DateDetailView
        if queryset is None:
            queryset = self.get_queryset()

        if slug is not None:
            qfiltered = queryset.filter(**{'slug': slug})
            try:
                project = qfiltered.get()
            except ObjectDoesNotExist:
                raise Http404(_(u"No %(verbose_name)s found matching the query") %
                          {'verbose_name': queryset.model._meta.verbose_name})
        else:
            project = queryset[0]

        if runslug is not None:

            qfiltered = project.runs.filter(**{'slug': runslug})
            try:
                self.run = qfiltered.get()
            except ObjectDoesNotExist:
                raise Http404(_(u"No %(verbose_name)s found matching the query") %
                          {'verbose_name': queryset.model._meta.verbose_name})
        else:
            self.run = project.runs.all()[0]
        ## Now Model Run Specifics:
        try:
            run_dir = os.path.join(project.product_directory, self.run.run_dir)
            self.H = pf.Header(run_dir, readp=False)
            self.P = {}
            self.P['run_dir'] = run_dir
            self.P['project'] = project
            self.P['projslug'] = project.slug
            self.P['projects'] = queryset.all()

            self.P['run_name'] = self.run.run_name
            self.P['run'] = self.run
            self.P['runslug'] = self.run.slug
            self.P['runs'] = project.runs.all()


        except:
            raise AttributeError(u"Cannot Open Run Directory For: "
                                 u"{0} with tracer: {1}."\
                                 .format(project.project_name, self.run.run_name))

        self.project = project

        return self



    def get_context_data(self, **kwargs):
        super(fpRunInteractive, self).get_context_data(**kwargs)
        context = kwargs
        context_object_name = self.get_context_object_name(self.object)

        if context_object_name:
            context[context_object_name] = self.object

        if self.request.method != 'POST':
            context['form'] = InteractivePlotForm(proj_set=self.P,
                                                   header=self.H)

            #TODO: Need to check how persistent this is.
            #self.request.session['header'] = self.H
            self.request.session['proj_set'] = self.P
        return context


    def post(self, *arg, **kwargs):
        super(fpRunInteractive, self).post(*arg, **kwargs)

        ## load information from session
        self.P = self.request.session['proj_set']
        
        if self.request.FILES:
            plotfile = self.request.FILES['plotfile']
            # assume json if 'application'
            if 'application' in plotfile.content_type:
                cd = json.load(plotfile)
                self.H = pf.Header( cd['run_dir'], nest=cd['nest'], readp=False)
                
                # also need to reset P
                self.kwargs['slug'] = cd['project']
                self.kwargs['runslug'] = cd['run']
                self.get_object(queryset = self.queryset)
                
                # process form
                form = InteractivePlotForm(header=self.H, proj_set=self.P, data=cd)
                
            else:
                # we'll use plotfile below
                self.H = None
        else:
            plotfile = None
            self.H = None
        
        if self.H is None:     
            run_dir = os.path.join(self.P['project'].product_directory, self.P['run'].run_dir)
        
            if 'nest' in self.request.POST:
                nest = True
            else:
                nest = False
    
            self.H = pf.Header( run_dir, nest=nest, readp=False)
            

            # process form
            form = InteractivePlotForm(header=self.H, proj_set=self.P, data=self.request.POST)
#           form = InteractivePlotForm( data=self.request.POST )

        if form.is_valid():

            cd = form.cleaned_data
#           
            # call the factory plotting routine
            # will return a dictionary that may 
            # added to the context
            
            ## check if a file was provided
            coords = None
            
            if plotfile:
                # assume a flighttrack, using plotfile from above
                if plotfile.content_type == 'text/plain':
                    coords = fpi_process_flighttrack(plotfile)
                    
            fpf = fpi.fpPlotFactory(self.H, cd,
                                    coords=coords,
                                    settings=self.settings)

            cd.update(fpf.process_request())
            cd.update({ 'MEDIA_URL' : settings.MEDIA_URL,
                       'MEDIA_ROOT' : settings.MEDIA_ROOT })
            context = cd

            #if not settings.DEBUG:
            #    del self.request.session['cd']
            #    del self.request.session['header']

            return render_to_response('fpi/fpi_view.html', context)

        else:
            #print form.errors.as_text()
            print 'form is not valid'
            form = dict(form=form)
            return render_to_response('fpi/fpi_form_error.html', form)
            


def header_ops(request):
    
    #if request.is_ajax():
    while True:
        q = request.GET.get('q')
        
        if q is not None:
            callrqst, slug, runslug ,= q.split('/')
            projects = fpProject.objects.all()
            project = projects.filter( **{'slug': slug}).get()
            if runslug == 'none':
                run = project.runs.all()[0]
            else:
                run = project.runs.filter(**{'slug': runslug}).get()
            
            run_dir = os.path.join(project.product_directory, run.run_dir)
            H = pf.Header(run_dir, readp=False)
            
            P = {}
            P['run_dir'] = run_dir
            P['project'] = project
            P['projslug'] = project.slug
            P['projects'] = projects

            P['run_name'] = run.run_name
            P['run'] = run
            P['runslug'] = run.slug
            P['runs'] = project.runs.all()
            
            request.session['proj_set'] = P
            
            form = InteractivePlotForm(proj_set=P,
                                       header=H)
            
            if callrqst == 'header':
                template = 'fpi/fpi_ajax_header.html'
            elif callrqst == 'project':
                template = 'fpi/fpi_ajax_project.html'
            data = {
                'form': form,
            }
            return render_to_response(template, data,
                context_instance=RequestContext(request))


def fpi_process_flighttrack(plotfile):
    """ process a simple standard flight track file """
    
    lines = plotfile.readlines()
    coords = []
    for line in lines:
        vals = line.strip().split(',')
        if len(vals) == 4:
            date = [datetime.strptime(vals[0], '%Y%m%d %H%M%S')]
            xyz = [float(i) for i in vals[1:]]
            vals = date + xyz
            coords.append(vals)
    return np.array(coords)


def image(request, fmt):

    #fmt = request.args[1]
    cd = request.session['cd']
    H = request.session['header']

atmos/atmos/templates/fpi/fpi_ajax_project.html
{% comment %}

Displays the menus for selecting the project and run

{% endcomment %}
<div id="projectops" id="leftcontrols">
	{{ form.projectID }} {{ form.run_dir }}
	<h3>FLEXPART Interactive Plotting Tool for:</h3>
	<p>
		<b>project:⇒</b> {{ form.project }}
	</p>
	<p>
		<b>run:⇒</b> {{ form.run }}
	</p>

	{% include 'fpi/fpi_ajax_header.html' %}
</div>

atmos/atmos/templates/fpi/fpi_form_error.html
{% extends 'base.html' %}


{% block content %}
<h2>There was an error processing your request.</h2>

<p>Please check the following parameters are correct:</p>

{{ form.errors }}

{% endblock %}

atmos/atmos/templates/fpi/fpi_interactive.html
{% extends 'base.html' %}

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"
      lang="en"
      metal:use-macro="here/main_template/macros/master"
      i18n:domain="sits">
{% block head %}
    <head>
        <title>{% block title %}Flexpart Interactive {% endblock %}</title>
        <script src="https://www.google.com/jsapi?key=ABQIAAAACwHKgL1igqJbFjRQJhUWyBTX27ALKqySBW6Nl1QKU6Q4S_KRExQv1nvf_WnanQrkPS07gIwL5yJyZQ" type="text/javascript"></script>
        <link rel="stylesheet" href="{{ MEDIA_URL }}style.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="{{ MEDIA_URL }}960min/960.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="{{ MEDIA_URL }}960min/reset.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="{{ MEDIA_URL }}960min/960_12_col.css" type="text/css" media="screen" />
        <script type="text/javascript">
        google.load("search", "1");
        google.load("jquery", "1.6.4");
        google.load("jqueryui", "1.8.16");
        </script>
        <!-- <script src="http://github.com/cowboy/jquery-bbq/raw/v1.2.1/jquery.ba-bbq.min.js" type="text/javascript"></script> -->
        <script src="{{ MEDIA_URL }}history.js/scripts/bundled/html4+html5/jquery.history.js"></script>
        <script src="http://www.openlayers.org/api/OpenLayers.js" type="text/javascript"></script>
        <script src="{{ MEDIA_URL }}fpi_OpenLayers.js" type="text/javascript"></script>
    <script type="text/javascript">
    $(document).ready(function()
    {
        j$ = jQuery.noConflict();
        init_OL();
        //j$('input').attr('disabled', 'disabled');
 
  
        
        j$('div#optionalparams').hide();
        j$('div#optionalmapparams').hide();
        j$('#spinner').hide();
        j$('select#p_end').attr('disabled', 'disabled');
        
        
        //hide optional parameters 
        j$('a#showparams').live( {
        	click: function(event) {
        	    event.preventDefault();
        	    j$('div#optionalparams').slideToggle('medium');
        	    }
        });
        

        //hide map parameters 
        j$('a#showmapparams').click( function(event)
        {
            event.preventDefault();
            j$('div#optionalmapparams').slideToggle('medium');
        });
        
        //swtich projects 
        j$('select#projects').live( {
            change: function() {
                q = ['project', this.value, 'none'].join('/');
                j$('#projectops').html('&nbsp;').load('{% url ops %}?q=' + q);
           }
        });

        //switch runs 
        j$('select#runs').live( {
            change: function() {
                proj = j$('select#projects').val();
                q = ['header', proj, this.value].join('/');
                j$('#headerops').html('&nbsp;').load('{% url ops %}?q=' + q);
            }    
        });

        
        
        
        // spinner 
        j$(document).ajaxStart(function() {
        	j$('#spinner').show();
        }).ajaxStop(function() {
        	j$('#spinner').hide();
        	j$('div#optionalparams').hide();
        });
        
        // clear file upload
        j$("#clearfile").click(function(event){
        	  event.preventDefault();
        	  
        	  j$("input#id_plotfile").replaceWith("<input type='file' name='plotfile' id='id_plotfile' />");
       	});

        
        
    });
    
/*     function historyCallback(e) {
    	
    }
    
    function switchProjects() {
    	var proj = j$.bbq.getState("project");
    	if (proj != undefined) {
    		q = ['project', proj, 'none'].join('/');
    		j$('#projectops').html('&nbsp;').load('{% url ops %}?q=' + q);	
    	};
    };
    
    function switchRuns() {
        var run = j$.bbq.getState("run") || j$('select#runs').val();
        var proj = j$.bbq.getState("project") || j$('select#projects').val();
        if (run != undefined) {
            q = ['header', proj, run].join('/');
            j$('#headerops').html('&nbsp;').load('{% url ops %}?q=' + q);  
        }
    }   */  
    
    </script>
</metal:javascriptslot> 
{% endblock head %}

<body>
{% block content %}
<metal:main fill-slot="main">
<div>    
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}
                     
       <form enctype="multipart/form-data" method="post" name="fpi_form"
       
                             action="{% url fpi-view %}" >{% csrf_token %}
                             
                             
							 <!--<input tal:attributes="name string:header; value H; type string:hidden;"type="hidden"> -->
            <!--  hidden fields -->

            <div class="grid_6 alpha">
           
            {% include 'fpi/fpi_ajax_project.html' %}
            <span id="spinner"><img src="{{ MEDIA_URL }}spinner.gif"/></span>
            </div>
            
            
            <div id="rightcontrols" class="grid_6 omega" style="background-color: rgb(85, 102, 153);">
                <div id="map" style="height:280px; width=320px;"></div>                
                <div  class="nostyle" id="controls" style="position: relative; left: 10px;">
                    <table id="controltoggle" border="0" cellpadding="2" cellspacing="2" >
                        <tbody>
                            <tr>
                                <td>
                                    <input name="type" value="nav" id="navtoggle" onclick="toggleControl(this);" checked="checked" type="radio"> <label for="navtoggle">navigate</label>
                                    <input name="type" value="line" id="linetoggle" onclick="toggleControl(this);" type="radio"> <label for="linetoggle">draw line</label>
                                    <input name="type" value="polygon" id="polygontoggle" onclick="toggleControl(this);" type="radio"> <label for="polygontoggle">draw square</label>
                                    <input name="type" value="drag" id="dragtoggle" onclick="toggleControl(this);" type="radio"> <label for="dragtoggle">drag feature</label>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <p>Use the controls above or <a href="#" id="showmapparams" ><font color='black'>fill in the boxes</font></a> below to select a bounding box and a cross-section
                                    line for the plots.
                                    </p>
                                </td>
                            </tr>    
                            
                        </tbody>
                    </table>
                </div>
                <div id="optionalmapparams">
			        <table class="gridtable"  id="mapinputs" border="0" cellpadding="2" cellspacing="2" >
                        <tbody>
                            <tr>
                               <td>
                                   <ul>
                                       <li type="disc">NOTE: click to set defaults: <button name="reset_latlon" type="button" onclick="resetCoords()">default</button>
                                       </li>
                                   </ul>
                               </td>
                            </tr>
                           
                            <tr>
                               <td>
                                   <div id="controls">
		  			
                                       <h3>box corners:</h3>
                                       <p>lower left lat : {{ form.llcrnrlat }}</p>
                                       <p>lower left lon : {{ form.llcrnrlon }}</p> 
                                       <p>upper right lat: {{ form.urcrnrlat }}</p>
                                       <p>upper right lon: {{ form.urcrnrlon }}</p>
                                       
                                       <input name="linebounds" value="" type="hidden">
                                       <h3>line coordinates:</h3>
                                       
                                       <p>lat 1:  {{ form.l_lat }} </p>
                                       <p>lon 1:  {{ form.l_lon }} </p>
                                       <p>lat 2:  {{ form.r_lat }} </p>
                                       <p>lon 2:  {{ form.r_lon }}</p>
                                       
                                   </div>
                               </td>
                           </tr>
                            <tr type="disc">
                                <td>NOTE: Click to set from Input: <button name="set_laton" type="button" onclick="setFromInput()">Set From Input</button></td>
                                
                            </tr>                           
                           
                           
                        </tbody>
                    </table>
                </div>
                <div class="nostyle" tal:condition="not:context/@@plone_portal_state/anonymous" style="height:220px; background-color: rgb(255, 204, 51);">
                    <div>
                        <p>Optional File Upload: <br>
                        </p>
                        <p>
                            {{ form.plotfile }}
                        </p>
                        <p><a href="#" id="clearfile">Clear</a></p>
                        
                        <p>
                            <em>NOTE: If uploading a flight file, coordinates
                            from map and time input from form will be ignored. Map coordinates will be
                            based on the flightrack.
                            </em>
                        </p>
                        <p>Format for flighttrack:<br/>
                        YYYYMMDD<span> </span>HHMMSS, lon, lat, elv
                        </p>
                        <p>You can also upload a .json file. Create a plot, and there will be a
                         link at the bottom for the configuration file that you may reuse by uploading it here.
                         
                        </p>
                        {% comment %}
                        <p>
                            {{ form.flight_movie }}
                            <em>make horizontal movie?</em> 
                            {{ form.timeseries }}
                           <em>plot time series?</em>
                        </p>
                        {% endcomment %}
                    </div>
                </div>
            </div>
	
        </form>
    </div>
</metal:main>
</div>

{% endblock %}


</body>

</html>

atmos/atmos/templates/fpi/fpproject_detail.html
{% extends 'base.html' %} {% block title %}Flexpart Project #{{
object.id }} - {% endblock %} {% block content %}
<div id="header">
	<h1>
		Flexpart Project: {{ object.project_name }} <span>{{ object.status }} 
	</h1>
</div>

{% block instructions %}{% endblock %}

<div id="description" class="grid_12">
    <div id="sidebar">
        <h2>Available Runs</h2>
        <table class="gridtable">
            <tr>
                <th>Run Name</th>
                <th>Link for Interactive Plotting</th>
            </tr>
            {% if object.runs %} {% for run in object.runs.all %}
            <tr>
                <td><p>
                        <a href="{% url run-detail run.id %}">{{ run.run_name }}</a>
                    </p></td>
                <td><a href="{% url fp-interactive object.slug run.slug %}">
                {{ object.slug }} : {{ tracer.run_dir }}</a></td>
            </tr>
            {% endfor %} {% endif %}
        </table>
    </div>
	<h2>Description</h2>
	<p>{{ object.project_description }}</p>

</div>

<div id="detail_container" class="grid_12">
	<div class="date">
		<p>Run generated by: {{ object.created_by}}</p>
		<p>Last modified: {{ object.updated_on }}</p>
	</div>

	<div class="grid_3 alpha">
		<h2>Information</h2>
		<p>{{ object.information }}</p>
	</div>
	<div class="grid_9 omega">
		<h2>Project Directory</h2>
		<p>{{ object.product_directory }}</p>
	</div>
</div>




{% endblock %}

atmos/atmos/templates/fpi/fpproject_list.html
{% extends 'base.html' %}
{% block title %}View Flexpart Projects{% endblock %}
{% block content %}
<div id="detail_container" class="grid_12">
<table class="gridtable">
    <tr>
        <th>Project ID</th>
        <th>Project Name</th>
        <th>Status</th>
        <th>Created By</th>
    </tr>
    {% for fpr in object_list %}
    <tr>
        <td><a href="{% url project-detail fpr.slug %}">{{ fpr.id }}</a></td>
        <td><a href="{% url project-detail fpr.slug %}">{{ fpr.project_name }}</a></td>
        <td>{{ fpr.status }}</td>
        <td>{{ fpr.created_by }}</td>
    </tr>
    {% endfor %}
</table>
</div>
{% endblock %}